name: Credentials Check

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Security Check with TruffleHog
      run: |
        pip install trufflehog
                
        trufflehog --regex --entropy=False ./
